// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_options.dart';

// ...

Future<void> main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbczQBw_Nfg7LM5la3zLTr-diQZ5HgOks',
    appId: '1:230498916877:web:615a8e830e3176d4515344',
    messagingSenderId: '230498916877',
    projectId: 'flutter-auth-firebase-fdd89',
    authDomain: 'flutter-auth-firebase-fdd89.firebaseapp.com',
    storageBucket: 'flutter-auth-firebase-fdd89.appspot.com',
    measurementId: 'G-J3WXXP4KWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoPIrkGmjBpZkrWJTDkw5G3WzDqgg8zOQ',
    appId: '1:230498916877:android:8cada9c5dde976d4515344',
    messagingSenderId: '230498916877',
    projectId: 'flutter-auth-firebase-fdd89',
    storageBucket: 'flutter-auth-firebase-fdd89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIq2ognBQvYeMD9laQb_NxxSSecf2QVuk',
    appId: '1:230498916877:ios:aa70c252cf261fc5515344',
    messagingSenderId: '230498916877',
    projectId: 'flutter-auth-firebase-fdd89',
    storageBucket: 'flutter-auth-firebase-fdd89.appspot.com',
    iosBundleId: 'com.example.myRealEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIq2ognBQvYeMD9laQb_NxxSSecf2QVuk',
    appId: '1:230498916877:ios:aa70c252cf261fc5515344',
    messagingSenderId: '230498916877',
    projectId: 'flutter-auth-firebase-fdd89',
    storageBucket: 'flutter-auth-firebase-fdd89.appspot.com',
    iosBundleId: 'com.example.myRealEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbczQBw_Nfg7LM5la3zLTr-diQZ5HgOks',
    appId: '1:230498916877:web:8d5c34edfe6f1965515344',
    messagingSenderId: '230498916877',
    projectId: 'flutter-auth-firebase-fdd89',
    authDomain: 'flutter-auth-firebase-fdd89.firebaseapp.com',
    storageBucket: 'flutter-auth-firebase-fdd89.appspot.com',
    measurementId: 'G-6ERJ1E1LZD',
  );
}
